-
  name: 'Livewire Conformance Tests'
  uriPattern: 'livewire-conformance-tests/{@action}'
  defaults:
    '@package': 'Sandstorm.Livewire'
    '@controller': 'Test'

-
  name: 'Test'
  uriPattern: 'livewire/update'
  defaults:
    '@package': 'Sandstorm.Livewire'
    '@controller': 'LivewireUpdate'
    '@action': 'update'
