
Neos:
  Flow:
    mvc:
      routes:
        'Sandstorm.Livewire':
          position: 'before Neos.Neos'
#  Fusion:
#    defaultContext:
#      Neos.Ui.Workspace: Neos\Neos\Ui\Fusion\Helper\WorkspaceHelper
#      Neos.Ui.StaticResources: Neos\Neos\Ui\Fusion\Helper\StaticResourcesHelper
#      Neos.Ui.PositionalArraySorter: Neos\Neos\Ui\Fusion\Helper\PositionalArraySorterHelper
